fujimi_otherbu:
  container_name: "fujimi_otherbu"
  image: fujimi_otherbu
  restart: always
  env_file: ./otherbu/.env.develop
  links:
    - fujimi_mysql:db
    - fujimi_redis:redis
    - fujimi_memcached:memcached
  volumes:
    - /var/run/otherbu
    - ./otherbu:/usr/src/otherbu
  command: uwsgi --ini scripts/uwsgi.ini

fujimi_todo:
  container_name: "fujimi_todo"
  image: fujimi_todo
  restart: always
  env_file: ./todo/.env.develop
  links:
    - fujimi_mysql:db
    - fujimi_redis:redis
    - fujimi_memcached:memcached
  volumes:
    - /var/run/todo
    - ./todo:/usr/src/todo
  command: uwsgi --ini scripts/uwsgi.ini

fujimi_todo_ws:
  container_name: "fujimi_todo_ws"
  image: fujimi_todo
  restart: always
  env_file: ./todo/.env.develop
  links:
    - fujimi_mysql:db
    - fujimi_redis:redis
    - fujimi_memcached:memcached
  volumes:
    - ./todo:/usr/src/todo
  command: ./application/server.py

fujimi_fuel-todo:
  container_name: "fujimi_fuel-todo"
  image: fujimi_fuel-todo
  restart: always
  env_file: ./fuel-todo/.env
  links:
    - fujimi_mysql:db
    - fujimi_redis:redis
    - fujimi_memcached:memcached
  volumes:
    - /var/run/fuel-todo
    - ./fuel-todo:/usr/src/fuel-todo
    - ./fuel-todo/php-fpm.d:/usr/local/etc/php-fpm.d

fujimi_trac:
  container_name: "fujimi_trac"
  image: fujimi_trac
  restart: always
  volumes:
    - ./trac/project:/usr/src/trac-project
  command: tracd /usr/src/trac-project

fujimi_nginx:
  container_name: "fujimi_nginx"
  image: fujimi_nginx
  restart: always
  ports:
    - "80:80"
    # - "443:443"
  links:
    - fujimi_otherbu:otherbu
    - fujimi_todo:todo
    - fujimi_todo_ws:todo_ws
    - fujimi_trac:trac
  volumes:
    - ./nginx/log:/var/log/nginx
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/vhosts:/etc/nginx/vhosts
    - ./blog:/usr/src/blog
  volumes_from:
    - fujimi_otherbu
    - fujimi_todo
    - fujimi_fuel-todo

fujimi_mysql:
  container_name: "fujimi_mysql"
  image: mysql:5.6
  restart: always
  ports:
    - "3306:3306"
  environment:
    - TZ=Asia/Tokyo
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./mysql/log:/var/log/mysql
    - ./mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
  volumes_from:
    - fujimi_storage

fujimi_redis:
  container_name: "fujimi_redis"
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - fujimi_storage
  command: redis-server --appendonly yes

fujimi_memcached:
  container_name: "fujimi_memcached"
  image: memcached:latest
  restart: always
  ports:
    - '11211:11211'
  volumes_from:
    - fujimi_storage

fujimi_storage:
  container_name: "fujimi_storage"
  image: busybox:latest
  volumes:
    - /var/lib/mysql
    - /data
