fujimi_otherbu:
  container_name: "fujimi_otherbu"
  image: fujimi_otherbu
  restart: always
  env_file: ./otherbu/.env.production
  volumes:
    - /var/run/otherbu
    - ./otherbu:/usr/src/otherbu
  command: uwsgi --ini scripts/uwsgi.ini

# fujimi_otherbu_staging:
#   container_name: "fujimi_otherbu_staging"
#   image: fujimi_otherbu
#   restart: always
#   env_file: ./otherbu/.env.staging
#   working_dir: "/usr/src/otherbu_staging"
#   volumes:
#     - /var/run/otherbu_staging
#     - ./otherbu:/usr/src/otherbu_staging
#   command: uwsgi --ini scripts/uwsgi_staging.ini

fujimi_todo:
  container_name: "fujimi_todo"
  image: fujimi_todo
  restart: always
  env_file: ./todo/.env.production
  volumes:
    - /var/run/todo
    - ./todo:/usr/src/todo
  command: uwsgi --ini scripts/uwsgi.ini

fujimi_todo_ws:
  container_name: "fujimi_todo_ws"
  image: fujimi_todo
  restart: always
  env_file: ./todo/.env.production
  volumes:
    - ./todo:/usr/src/todo
  command: ./application/server.py

fujimi_fuel-todo:
  container_name: "fujimi_fuel-todo"
  image: fujimi_fuel-todo
  restart: always
  env_file: ./fuel-todo/.env
  volumes:
    - /var/run/fuel-todo
    - ./fuel-todo:/usr/src/fuel-todo
    - ./fuel-todo/php-fpm.d:/usr/local/etc/php-fpm.d

fujimi_trac:
  container_name: "fujimi_trac"
  image: fujimi_trac
  restart: always
  volumes:
    - ./trac/project:/usr/src/trac-project
  command: tracd /usr/src/trac-project

fujimi_nginx:
  container_name: "fujimi_nginx"
  image: fujimi_nginx
  restart: always
  ports:
    - "80:80"
    # - "443:443"
  links:
    - fujimi_otherbu:otherbu
    # - fujimi_otherbu_staging:otherbu_staging
    - fujimi_todo_ws:todo_ws
    - fujimi_trac:trac
  volumes:
    - ./nginx/log:/var/log/nginx
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/vhosts:/etc/nginx/vhosts
  volumes_from:
    - fujimi_otherbu
    # - fujimi_otherbu_staging
    - fujimi_todo
    - fujimi_fuel-todo
