fujimi_otherbu_prod:
  container_name: "fujimi_otherbu_prod"
  image: fujimi_otherbu
  restart: always
  env_file: ./otherbu/.env.production
  working_dir: "/usr/src/otherbu_prod"
  volumes:
    - /var/run/otherbu
    - ./otherbu:/usr/src/otherbu_prod
  command: uwsgi --ini scripts/uwsgi_prod.ini

fujimi_otherbu_staging:
  container_name: "fujimi_otherbu_staging"
  image: fujimi_otherbu
  restart: always
  env_file: ./otherbu/.env.staging
  working_dir: "/usr/src/otherbu_staging"
  volumes:
    - /var/run/otherbu
    - ./otherbu:/usr/src/otherbu_staging
  command: uwsgi --ini scripts/uwsgi_staging.ini

fujimi_todo_prod:
  container_name: "fujimi_todo_prod"
  image: fujimi_todo
  restart: always
  env_file: ./todo/.env.production
  working_dir: "/usr/src/todo_prod"
  volumes:
    - /var/run/todo
    - ./todo:/usr/src/todo_prod
  command: uwsgi --ini scripts/uwsgi_prod.ini

fujimi_todo_ws_prod:
  container_name: "fujimi_todo_ws_prod"
  image: fujimi_todo
  restart: always
  env_file: ./todo/.env.production
  working_dir: "/usr/src/todo_prod"
  volumes:
    - ./todo:/usr/src/todo_prod
  command: ./application/server.py

fujimi_fuel-todo:
  container_name: "fujimi_fuel-todo"
  image: fujimi_fuel-todo
  restart: always
  env_file: ./fuel-todo/.env
  volumes:
    - /var/run/php-fpm
    - ./fuel-todo:/usr/src/fuel-todo
    - ./fuel-todo/php-fpm.d:/usr/local/etc/php-fpm.d

fujimi_trac:
  container_name: "fujimi_trac"
  image: fujimi_trac
  restart: always
  volumes:
    - ./trac/project:/usr/src/trac-project
  command: tracd /usr/src/trac-project

fujimi_nginx:
  container_name: "fujimi_nginx"
  image: fujimi_nginx
  restart: always
  ports:
    - "80:80"
    # - "443:443"
  links:
    - fujimi_otherbu_prod:otherbu_prod
    - fujimi_otherbu_staging:otherbu_staging
    - fujimi_todo_prod:todo_prod
    - fujimi_todo_ws_prod:todo_ws
    - fujimi_trac:trac
  volumes:
    - ./nginx/log:/var/log/nginx
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/vhosts:/etc/nginx/vhosts
  volumes_from:
    - fujimi_otherbu_prod
    - fujimi_otherbu_staging
